config/routes.rb
NewUser::Application.routes.draw do
  resources :people do
    collection do
      get :form_new
    end
  end

  resources :users do
    collection do
      get :edit_links,:new_link
    end
  end

root :to => 'users#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/person.rb
class Person < ActiveRecord::Base
   attr_accessible :person_type,:first_name, :last_name, :email, :phone_home, :phone_cell, :gender, :user_id
  validates :first_name,:last_name,:phone_home,:phone_cell,:email,:presence=>true
  validates :phone_home,:phone_cell,:numericality=>true
  validates :email,:format=>{:with => /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/,
:message => "Enter a valid email address." }
  belongs_to :user
  
  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
  validates :email_address,:presence=>true,:format=>{:with => /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/,
:message => "Enter a valid email address." }
  has_many :persons
  accepts_nested_attributes_for :persons
  def new_person_attributes=attributes
  attributes.each do |record|
  persons.build(record)
  end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all
    redirect_to :controller=>"users",:action=>"index",:users=>@users
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new
    @users=User.find(:all)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
  
  def form_new
    puts "the params are#{params}"
    render :partial => 'users/new_form', :locals => {:f => Person.new}
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  include UsersHelper
  include PeopleHelper
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @persons=@user.persons
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
      respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    # @person = @user.persons.build(:user_id=>@user.id)
  end
  # def edit_link
    # @user = User.find(params[:id])
      # @person = @user.persons.build(:user_id=>@user.id)
      # render 'edit'
  # end

  # POST /users
  # POST /users.json
  def create
    @user = User.create(params[:user])
    puts @user.id
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
  def add_hospital_link(name)
  link_to name, '#', :class => "add_hospital"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def edit_link
        puts "the params helper#{params}"
    @user = User.find(params[:id])
      @person = @user.persons.build(:user_id=>@user.id)
      render 'edit'
  end
  def new_link
    puts "i am in new link with params#{params}"
    @user= User.new
    @person = @user.persons.build
    render :partial=>'new_form'
  end
   
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewUser</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_edit_form.html.erb
   <%=f.fields_for :persons do |p|%>
  <div class="field">
    <%= p.label :first_name %><br />
    <%= p.text_field :first_name %>
    </div>
    <div class="field">
    <%= p.label :last_name %><br />
    <%= p.text_field :last_name %>
  </div>
<div class="field">
    <%= p.label :email %><br />
    <%= p.text_field :email %>
  </div>
  <div class="field">
    <%= p.label :phone_home %><br />
    <%= p.text_field :phone_home %>
  </div>
  <div class="field">
    <%= p.label :phone_cell %><br />
    <%= p.text_field :phone_cell %>
  </div>
  <div class="field">
    <%= p.label :gender %><br />
    Male <%= p.radio_button :gender, "Male" %>
    Female<%= p.radio_button :gender,"Female" %>
  </div>
  <div class="field">
  	<%= p.label :type%><br />
    <%= p.select :person_type,["Camper","Employee","Parent"] %>
  </div>
  <%end%> 

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
    </div>
    <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
<div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_home %><br />
    <%= f.text_field :phone_home %>
  </div>
  <div class="field">
    <%= f.label :phone_cell %><br />
    <%= f.text_field :phone_cell %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.select :gender,["Male","Female"] %>
  </div>
  <div class="field">
  	<%= f.label :type%><br />
    <%= f.select :person_type,["Camper","Employee","Parent"] %>
  </div>
  <div class="field">
  	<%= f.label :user_id%><br />
    <%= f.select :user_id, @users.map {|u| [u.email_address, u.id] unless @users.empty?} ,:prompt=>true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/form_new.js.erb
$("#person_form").prepend("<%=escape_javascript(render :partial=>'users/new_form',:locals => { :f => @f }) %>");

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>
<%unless @person.nil?%>
<tr>
Name : <%=@person.full_name%><br />
User : <%=@person.user.email_address unless @person.user.nil?%> <br />
</tr>
<%end%>
<tr>
<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>
</tr>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <%end%>
  <h1>User Details</h1>
<div class="field">
    <%= f.label :email_address %><br />
    <%= f.text_field :email_address %>
  </div>
   <div id="person_form"></div>
   <div>
   	<%=f.fields_for :persons do |p|%>
  <div class="field">
    <%= p.label :first_name %><br />
    <%= p.text_field :first_name %>
    </div>
    <div class="field">
    <%= p.label :last_name %><br />
    <%= p.text_field :last_name %>
  </div>
<div class="field">
    <%= p.label :email %><br />
    <%= p.text_field :email %>
  </div>
  <div class="field">
    <%= p.label :phone_home %><br />
    <%= p.text_field :phone_home %>
  </div>
  <div class="field">
    <%= p.label :phone_cell %><br />
    <%= p.text_field :phone_cell %>
  </div>
  <div class="field">
    <%= p.label :gender %><br />
    Male <%= p.radio_button :gender, "Male" %>
    Female<%= p.radio_button :gender,"Female" %>
  </div>
  <div class="field">
  	<%= p.label :type%><br />
    <%= p.select :person_type,["Camper","Employee","Parent"] %>
  </div>
  <%end%>
   </div>
  <div>
     
  </div>
  <!-- <h1>Person Details</h1>
   <%=f.fields_for :persons do |p|%>
  <div class="field">
    <%= p.label :first_name %><br />
    <%= p.text_field :first_name %>
    </div>
    <div class="field">
    <%= p.label :last_name %><br />
    <%= p.text_field :last_name %>
  </div>
<div class="field">
    <%= p.label :email %><br />
    <%= p.text_field :email %>
  </div>
  <div class="field">
    <%= p.label :phone_home %><br />
    <%= p.text_field :phone_home %>
  </div>
  <div class="field">
    <%= p.label :phone_cell %><br />
    <%= p.text_field :phone_cell %>
  </div>
  <div class="field">
    <%= p.label :gender %><br />
    Male <%= p.radio_button :gender, "Male" %>
    Female<%= p.radio_button :gender,"Female" %>
  </div>
  <div class="field">
  	<%= p.label :type%><br />
    <%= p.select :person_type,["Camper","Employee","Parent"] %>
  </div>
  <%end%>  -->
  
  <div class="actions">
  	<input type="hidden" id="f" value="<%=f%>" />
    <%= f.submit %> 
   </div>
<% end %>

app/views/users/_new_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <%end%>
  <h1>User Details</h1>
<div class="field">
    <%= f.label :email_address %><br />
    <%= f.text_field :email_address %>
  </div>
  <h1>Person Details</h1>
   <%=f.fields_for :persons do |p|%>
  <div class="field">
    <%= p.label :first_name %><br />
    <%= p.text_field :first_name %>
    </div>
    <div class="field">
    <%= p.label :last_name %><br />
    <%= p.text_field :last_name %>
  </div>
<div class="field">
    <%= p.label :email %><br />
    <%= p.text_field :email %>
  </div>
  <div class="field">
    <%= p.label :phone_home %><br />
    <%= p.text_field :phone_home %>
  </div>
  <div class="field">
    <%= p.label :phone_cell %><br />
    <%= p.text_field :phone_cell %>
  </div>
  <div class="field">
    <%= p.label :gender %><br />
    Male <%= p.radio_button :gender, "Male" %>
    Female<%= p.radio_button :gender,"Female" %>
  </div>
  <div class="field">
  	<%= p.label :type%><br />
    <%= p.select :person_type,["Camper","Employee","Parent"] %>
  </div>
  <%end%> 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %> | <%= add_hospital_link("New Person") %>

app/views/users/index.html.erb
<h1>Listing Users</h1>
<%unless @users.empty?%>

<table>
  <tr>
    <th>Email Address</th>
   </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email_address %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
<% end %>
</table>
<%end%>


<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %> | <%= add_hospital_link("Add Person") %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<%unless @user.nil?%>
<p>
  <b>Email address</b>
  <%= @user.email_address %> <br />
  <b>Persons</b>
<%unless @persons.empty?%>
<table>
	<tr style="background-color: yellow;">
		<td>Name</td>
		<td>Email</td>
		<td>Gender</td>
		<td>Type</td>
	</tr>
	<body>
<%@persons.each do |person|%>
<tr>
	<td><%=person.full_name%></td>
	<td><%=person.email%></td>
	<td><%=person.gender%></td>
	<td><%=person.person_type%></td>
</tr>    
<%end%>
</body>
</table>
<%end%>
</p>
<%end%>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>